name: client
on:
  push:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OCTOPRINT_BLINKRS_UI_ROOT: "/printing"
      OCTOPRINT_BLINKRS_API_ROOT: "https://krumpled.com/printing/api/"
      OCTOPRINT_BLINKRS_LOGIN_URL: "https://krumpled.com/printing/api/auth/start"
      OCTOPRINT_BLINKRS_SNAPSHOT_URL: "https://krumpled.com/printing/api/control/snapshot"
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm i
      - run: npm run test:ember
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm run build
      - name: rename-bundle
        run: mv dist octoprint-blinkrs-dist
      - name: create-bundle
        run: tar cvzf octoprint-blinkrs-dist.tar.gz octoprint-blinkrs-dist
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./client/octoprint-blinkrs-dist.tar.gz
